databases:
  - name: ranksprint-postgres
    plan: free
    databaseName: ranksprint
    user: ranksprint

services:
  - type: web
    name: ranksprint-web
    runtime: node
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: ranksprint-postgres
          property: connectionString
      - key: VITE_FIREBASE_API_KEY
        value: AIzaSyDOVgglDopjbSfhxk-jWg42cK4M6rOT1h4
      - key: VITE_FIREBASE_AUTH_DOMAIN
        value: cubeicons-ad59f.firebaseapp.com
      - key: VITE_FIREBASE_PROJECT_ID
        value: cubeicons-ad59f
      - key: VITE_FIREBASE_APP_ID
        value: 1:238451962485:web:3f8459533366426be6fe3c
      - key: VITE_FIREBASE_STORAGE_BUCKET
        value: cubeicons-ad59f.firebasestorage.app
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        value: "238451962485"
      - key: VITE_GOOGLE_CLIENT_ID
        value: 238451962485-m2r2lnqo7h09ef044riocjvti77vakou.apps.googleusercontent.com
